#!/usr/bin/env bash

# set -x

print_usage() {
	echo -e "\n$(basename $0) -s SCHEMA NODE [-- PG_ARGS]"
}

schema=""
while getopts ":hs:" opt
do
    case ${opt} in
        s)
            schema="${OPTARG}"
            ;;
        h)
            print_usage
            exit 0
            ;;
        \?)
            ;;
    esac
done
shift $((OPTIND - 1))

if [[ -z "${schema}" ]]
then
	print_usage 1>&2
	exit 1
fi

node="${1}"

if [[ ! -e "${node}"  ]]
then
    echo "Node does not exist: ${node}." 1>&2
    exit 1
fi

shift 1

if [[ "${1}" = "--" ]]
then
    shift 1
fi

pg_copy_csv(){
    schema="${1}"
    file="${2}"
    name_with_extension="${file##*/}"
    tablename="${name_with_extension%.csv}"
    shift 2
    echo -e "Copying ${tablename}."
	psql "${@}" -c"copy ${schema}.${tablename} from stdin with null 'NULL';" < "${file}"
}

if [ -f "${node}" ]
then
    pg_copy_csv "${schema}" "${node}" "${@}"
    exit
fi

while read p
do
    pg_copy_csv "${schema}" "${p}" "${@}"
done < <( find "${node}" -mindepth 1 -maxdepth 1 \
    ! -path \*/.\* -iname \*.csv -type f \
    ! -size 0)
